# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 02:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0002_auto_20160322_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1850)]),
        ),
    ]
