# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0004_auto_20160322_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_written',
            new_name='dateWritten',
        ),
    ]
