# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0012_auto_20160322_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='film_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='filmlist.Film'),
        ),
    ]
