# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0013_review_film_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='filmlist.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='film_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmlist.Film'),
        ),
    ]
