# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0014_auto_20160322_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='film_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='filmlist.Film'),
        ),
    ]
