# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0017_auto_20160322_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('syrup_type', models.CharField(blank=True, max_length=15)),
                ('temperature', models.CharField(max_length=4)),
                ('tea_type', models.CharField(max_length=15)),
                ('topping_type', models.CharField(max_length=15)),
                ('topping_flavour', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BTShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('location', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('date_written', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=250)),
                ('rating', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
