# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0020_auto_20160322_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='shop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='filmlist.Shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
