# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0023_auto_20160322_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='drink_name',
        ),
    ]
