# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0025_auto_20160322_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='temperature',
            field=models.CharField(choices=['Cold', 'Hot', 'Hot/Cold'], max_length=8),
        ),
    ]
