# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0026_auto_20160323_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='tea_form',
            field=models.CharField(choices=['Fruit', 'Milk', 'Special'], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='tea_type',
            field=models.CharField(choices=['Black', 'Green'], max_length=5),
        ),
    ]
