# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0027_auto_20160323_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='drink_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='filmlist.Drink'),
            preserve_default=False,
        ),
    ]
