# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0028_review_drink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='drink_name',
        ),
        migrations.AddField(
            model_name='location',
            name='franchise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='filmlist.Franchise'),
        ),
    ]
