# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0031_auto_20160325_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
