# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0035_auto_20160325_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='franchise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmlist.Franchise'),
        ),
        migrations.AlterField(
            model_name='location',
            name='franchise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmlist.Franchise'),
        ),
    ]
