# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0038_auto_20160325_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='franchise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='filmlist.Franchise'),
        ),
        migrations.AlterField(
            model_name='location',
            name='franchise_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise', to='filmlist.Franchise'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
