# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmlist', '0041_auto_20160326_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='owner',
            new_name='username',
        ),
    ]
