# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20160322_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='film_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writer',
        ),
    ]
