# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_auto_20160322_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTDrink',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='ShopRating',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='BTShop',
            new_name='Shop',
        ),
    ]
