# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0021_auto_20160322_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
