# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_auto_20160322_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
