# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0030_auto_20160325_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
