# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0040_auto_20160326_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='owner',
        ),
    ]
