# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 18:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0042_auto_20160326_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='syrup_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drink',
            name='topping_type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
