# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0043_auto_20160326_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='age',
        ),
        migrations.AlterField(
            model_name='drink',
            name='tea_type',
            field=models.CharField(choices=['Black', 'Green', 'Special'], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
