# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0044_auto_20160327_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='franchise_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='franchise_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='franchise_name',
        ),
        migrations.AddField(
            model_name='drink',
            name='franchise_drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_drink', to='restapi.Franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='franchise_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_location', to='restapi.Franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='franchise_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_review', to='restapi.Franchise'),
            preserve_default=False,
        ),
    ]
