# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0046_auto_20160329_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='franchise_name',
            new_name='franchise_drink',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='franchise_name',
            new_name='franchise_location',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='franchise_name',
            new_name='franchise_review',
        ),
    ]
